# Generated by Django 3.1.3 on 2021-01-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210111_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
